CREATE TABLE ALL_STATE.TRAIN (
  `customer_ID` int(11) NOT NULL,
  `shopping_pt` tinyint(4) NOT NULL,
  `record_type` tinyint(4) DEFAULT NULL,
  `day` tinyint(4) DEFAULT NULL,
  `time` tinyint(4) DEFAULT NULL,
  `state` tinyint(4) DEFAULT NULL,
  `location` int(11) DEFAULT NULL,
  `group_size` tinyint(4) DEFAULT NULL,
  `homeowner` tinyint(4) DEFAULT NULL,
  `car_age` tinyint(4) DEFAULT NULL,
  `car_value` tinyint(4) DEFAULT NULL,
  `risk_factor` tinyint(4) DEFAULT NULL,
  `age_oldest` tinyint(4) DEFAULT NULL,
  `age_youngest` tinyint(4) DEFAULT NULL,
  `married_couple` tinyint(4) DEFAULT NULL,
  `C_previous` tinyint(4) DEFAULT NULL,
  `duration_previous` tinyint(4) DEFAULT NULL,
  `A` tinyint(4) DEFAULT NULL,
  `B` tinyint(4) DEFAULT NULL,
  `C` tinyint(4) DEFAULT NULL,
  `D` tinyint(4) DEFAULT NULL,
  `E` tinyint(4) DEFAULT NULL,
  `F` tinyint(4) DEFAULT NULL,
  `G` tinyint(4) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  PRIMARY KEY (`customer_ID`,`shopping_pt`),
  KEY `LOCATION_IDX` (`location`),
  KEY `STATE_IDX` (`state`),
  KEY `GROUP_IDX` (`group_size`),
  KEY `AGE_OLD_IDX` (`age_oldest`),
  KEY `AGE_YOUNG_IDX` (`age_youngest`),
  KEY `CAR_AGE_IDX` (`car_age`),
  KEY `RECORD_TYPE_IDX` (`record_type`),
  KEY `MARRIED_IDX` (`married_couple`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALL_STATE.TEST (
  `customer_ID` int(11) NOT NULL,
  `shopping_pt` tinyint(4) NOT NULL,
  `record_type` tinyint(4) DEFAULT NULL,
  `day` tinyint(4) DEFAULT NULL,
  `time` tinyint(4) DEFAULT NULL,
  `state` tinyint(4) DEFAULT NULL,
  `location` int(11) DEFAULT NULL,
  `group_size` tinyint(4) DEFAULT NULL,
  `homeowner` tinyint(4) DEFAULT NULL,
  `car_age` tinyint(4) DEFAULT NULL,
  `car_value` tinyint(4) DEFAULT NULL,
  `risk_factor` tinyint(4) DEFAULT NULL,
  `age_oldest` tinyint(4) DEFAULT NULL,
  `age_youngest` tinyint(4) DEFAULT NULL,
  `married_couple` tinyint(4) DEFAULT NULL,
  `C_previous` tinyint(4) DEFAULT NULL,
  `duration_previous` tinyint(4) DEFAULT NULL,
  `A` tinyint(4) DEFAULT NULL,
  `B` tinyint(4) DEFAULT NULL,
  `C` tinyint(4) DEFAULT NULL,
  `D` tinyint(4) DEFAULT NULL,
  `E` tinyint(4) DEFAULT NULL,
  `F` tinyint(4) DEFAULT NULL,
  `G` tinyint(4) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  PRIMARY KEY (`customer_ID`,`shopping_pt`),
  KEY `LOCATION_IDX` (`location`),
  KEY `STATE_IDX` (`state`),
  KEY `GROUP_IDX` (`group_size`),
  KEY `AGE_OLD_IDX` (`age_oldest`),
  KEY `AGE_YOUNG_IDX` (`age_youngest`),
  KEY `CAR_AGE_IDX` (`car_age`),
  KEY `RECORD_TYPE_IDX` (`record_type`),
  KEY `MARRIED_IDX` (`married_couple`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ALL_STATE.TRAIN_TRUNC (
  `customer_ID` int(11) NOT NULL,
  `shopping_pt` tinyint(4) NOT NULL,
  `record_type` tinyint(4) DEFAULT NULL,
  `day` tinyint(4) DEFAULT NULL,
  `time` tinyint(4) DEFAULT NULL,
  `state` tinyint(4) DEFAULT NULL,
  `location` int(11) DEFAULT NULL,
  `group_size` tinyint(4) DEFAULT NULL,
  `homeowner` tinyint(4) DEFAULT NULL,
  `car_age` tinyint(4) DEFAULT NULL,
  `car_value` tinyint(4) DEFAULT NULL,
  `risk_factor` tinyint(4) DEFAULT NULL,
  `age_oldest` tinyint(4) DEFAULT NULL,
  `age_youngest` tinyint(4) DEFAULT NULL,
  `married_couple` tinyint(4) DEFAULT NULL,
  `C_previous` tinyint(4) DEFAULT NULL,
  `duration_previous` tinyint(4) DEFAULT NULL,
  `A` tinyint(4) DEFAULT NULL,
  `B` tinyint(4) DEFAULT NULL,
  `C` tinyint(4) DEFAULT NULL,
  `D` tinyint(4) DEFAULT NULL,
  `E` tinyint(4) DEFAULT NULL,
  `F` tinyint(4) DEFAULT NULL,
  `G` tinyint(4) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `y_customer_ID` int(11) NOT NULL,
  `y_shopping_pt` tinyint(4) NOT NULL,
  `y_record_type` tinyint(4) DEFAULT NULL,
  `y_day` tinyint(4) DEFAULT NULL,
  `y_time` tinyint(4) DEFAULT NULL,
  `y_state` tinyint(4) DEFAULT NULL,
  `y_location` int(11) DEFAULT NULL,
  `y_group_size` tinyint(4) DEFAULT NULL,
  `y_homeowner` tinyint(4) DEFAULT NULL,
  `y_car_age` tinyint(4) DEFAULT NULL,
  `y_car_value` tinyint(4) DEFAULT NULL,
  `y_risk_factor` tinyint(4) DEFAULT NULL,
  `y_age_oldest` tinyint(4) DEFAULT NULL,
  `y_age_youngest` tinyint(4) DEFAULT NULL,
  `y_married_couple` tinyint(4) DEFAULT NULL,
  `y_C_previous` tinyint(4) DEFAULT NULL,
  `y_duration_previous` tinyint(4) DEFAULT NULL,
  `y_A` tinyint(4) DEFAULT NULL,
  `y_B` tinyint(4) DEFAULT NULL,
  `y_C` tinyint(4) DEFAULT NULL,
  `y_D` tinyint(4) DEFAULT NULL,
  `y_E` tinyint(4) DEFAULT NULL,
  `y_F` tinyint(4) DEFAULT NULL,
  `y_G` tinyint(4) DEFAULT NULL,
  `y_cost` int(11) DEFAULT NULL,
  `SAMPLE_NUM` tinyint(4) NOT NULL,
  PRIMARY KEY (`customer_ID`,`shopping_pt`,`SAMPLE_NUM`),
  KEY `shopping_pt_IDX` (`shopping_pt`),
  KEY `record_type` (`record_type`),
  KEY `y_shopping_pt_IDX` (`y_shopping_pt`),
  KEY `y_record_type` (`y_record_type`),
  KEY `SAMPLE_NUM_IDX` (`SAMPLE_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
